#include <Bonobo.idl>

module GNOME {

	module EOG {

		/* URIs are just plain strings, but we use a typedef to make
		 * the interface definitions clearer.
		 */
		typedef string URI;
           	typedef sequence<URI> URIList;
                
		interface CollectionView : Bonobo::Unknown {
			oneway void loadURIList (in URIList locations);
		};
	};
};
