/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Interpolation type");
gchar *s = N_("Transparency type");
gchar *s = N_("Check size");
gchar *s = N_("Dark checks\n"
              "Midtone checks\n"
              "Light checks\n"
              "Black only\n"
              "Gray only\n"
              "White only\n"
              "");
gchar *s = N_("Small\n"
              "Medium\n"
              "Large\n"
              "");
gchar *s = N_("Nearest neighbor\n"
              "Bilinear\n"
              "Hyperbolic\n"
              "");
gchar *s = N_("Two-pass scrolling");
gchar *s = N_("Dither type");
gchar *s = N_("None\n"
              "Normal (pseudocolor)\n"
              "Maximum (high color)\n"
              "");
gchar *s = N_("Display");
gchar *s = N_("Image Windows");
gchar *s = N_("Use scrollbars");
gchar *s = N_("Never\n"
              "Only if image does not fit\n"
              "");
gchar *s = N_("Pick window size and zoom factor automatically");
gchar *s = N_("Open images in a new window");
gchar *s = N_("Full Screen");
gchar *s = N_("Use scrollbars");
gchar *s = N_("Never\n"
              "Only if image does not fit\n"
              "");
gchar *s = N_("Use 1:1 zoom factor");
gchar *s = N_("Use same zoom factor as image window");
gchar *s = N_("Fit all images to screen");
gchar *s = N_("Fit standard-sized images to screen");
gchar *s = N_("Put a bevel around the edge of the screen");
gchar *s = N_("Viewers");
