/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Interpolation type");
gchar *s = N_("Transparency type");
gchar *s = N_("Check size");
gchar *s = N_("Dark checks");
gchar *s = N_("Midtone checks");
gchar *s = N_("Light checks");
gchar *s = N_("Black only");
gchar *s = N_("Gray only");
gchar *s = N_("White only");
gchar *s = N_("Small");
gchar *s = N_("Medium");
gchar *s = N_("Large");
gchar *s = N_("Nearest neighbor (fastest, low quality)");
gchar *s = N_("Bilinear (normal)");
gchar *s = N_("Hyperbolic (slowest, best quality)");
gchar *s = N_("Two-pass scrolling");
gchar *s = N_("Dither type");
gchar *s = N_("None");
gchar *s = N_("Normal (pseudocolor)");
gchar *s = N_("Maximum (high color)");
gchar *s = N_("Display");
gchar *s = N_("Image Windows");
gchar *s = N_("Use scrollbars");
gchar *s = N_("Never");
gchar *s = N_("Only if image does not fit");
gchar *s = N_("Pick window size and zoom factor automatically");
gchar *s = N_("Open images in a new window");
gchar *s = N_("Full Screen");
gchar *s = N_("Use scrollbars");
gchar *s = N_("Never");
gchar *s = N_("Only if image does not fit");
gchar *s = N_("Use 1:1 zoom factor");
gchar *s = N_("Use same zoom factor as image window");
gchar *s = N_("Fit all images to screen");
gchar *s = N_("Fit standard-sized images to screen");
gchar *s = N_("Put a bevel around the edge of the screen");
gchar *s = N_("Viewers");
