name: eog
version: git
adopt-info: eog
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpeas-1.0:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpeas-1.0
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/eog:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/eog
  /usr/share/eog:
    bind: $SNAP/usr/share/eog

slots:
  # for GtkApplication registration
  eog:
    interface: dbus
    bus: session
    name: org.gnome.eog

apps:
  eog:
    common-id: org.gnome.eog.desktop
    command: usr/bin/eog
    extensions: [gnome-3-28]
    plugs:
      - home
      - gsettings
      - network
      - mount-observe
      - removable-media
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/eog:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/eog:$LD_LIBRARY_PATH
      GI_TYPELIB_PATH: $SNAP/usr/lib/eog/girepository-1.0:$SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/gnome-platform/usr/lib/girepository-1.0:$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/gnome-platform/usr/lib/python3/dist-packages
      
parts:
  cairo:
    source-branch: '1.16'
    source: git://anongit.freedesktop.org/git/cairo
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --enable-pdf
      - --enable-ps
      - --enable-xlib
      - --enable-png
      - --enable-tee
      - --enable-svg
      - --enable-perf-utils
      - --disable-silent-rules
      - --disable-maintainer-mode
    build-packages:
      - libfontconfig1-dev
      - libfreetype6-dev
      - libpixman-1-dev
      - libpoppler-dev
      - libx11-dev
      - libxext-dev
      - libxcb-render0-dev
  librsvg:
    after: [ cairo ]
    source: https://gitlab.gnome.org/GNOME/librsvg.git
    source-branch: librsvg-2.44
    plugin: autotools
    configflags: [ --prefix=/usr ]
    build-packages:
      - cargo
      - libcroco3-dev
      - libfreetype6-dev
      - libgdk-pixbuf2.0-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libpango1.0-dev
      - libxml2-dev
      - rustc
      - valac
  eog:
    after: [librsvg]
    source: .
    source-type: git
    parse-info: [usr/share/metainfo/org.gnome.eog.metainfo.xml]
    plugin: meson
    meson-parameters: [--prefix=/usr, -Dintrospection=true, -Dlibportal=false]
    organize:
      snap/eog/current/usr: usr
    override-build: |
      sed -i.bak -e 's|=org.gnome.eog$|=${SNAP}/meta/gui/org.gnome.eog.svg|g' data/org.gnome.eog.desktop.in.in
      sed -i.bak -e 's|media: media,|media: media, symlink_media: false,|g' help/meson.build
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/scalable/apps/org.gnome.eog.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp snapbuild/data/org.gnome.eog.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    build-packages:
      - appstream-util
      - desktop-file-utils
      - gettext
      - gnome-common
      - gsettings-desktop-schemas-dev
      - gobject-introspection
      - gtk-doc-tools
      - intltool
      - libatk1.0-dev
      - libexempi-dev
      - libexif-dev
      - libgdk-pixbuf2.0-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgnome-desktop-3-dev
      - libgtk-3-dev
      - libjpeg-dev
      - liblcms2-dev
      - libpeas-dev
      - pkg-config
      - shared-mime-info
      - valac
      - yelp-tools
      - zlib1g-dev

  libraries:
    plugin: nil
    stage-packages:
      - libexif12
      - libexempi3
    prime:
      - "usr/lib/*/libexif*"
      - "usr/lib/*/libexempi*"
